#index:
#    path: /
#    controller: App\Controller\DefaultController::index
controllers:
  resource: '../src/Controller/'
  type:     annotation

authentication_token:
  path: /login
  methods: ["POST"]
